name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    
    - name: Install dependencies
      run: poetry install
    
    - name: Build with PyInstaller
      run: |
        poetry run pyinstaller directory_printer.spec
    
    - name: Zip Windows artifacts
      if: matrix.os == 'windows-latest'
      run: |
        cd dist
        7z a ../directory-printer-windows.zip directory-printer.exe
      shell: bash
    
    - name: Zip Linux artifacts
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd dist
        zip -r ../directory-printer-linux.zip directory-printer
      shell: bash
    
    - name: Zip macOS artifacts
      if: matrix.os == 'macos-latest'
      run: |
        cd dist
        zip -r ../directory-printer-macos.zip directory-printer.app
      shell: bash
    
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          directory-printer-windows.zip
          directory-printer-linux.zip
          directory-printer-macos.zip 